import assert from "node:assert/strict";
import { test } from "node:test";
import { hashPassword, verifyPassword } from "../src/utils/password.js";

// Generated by the legacy `argon2` npm package (v0.45.x) with its defaults:
// argon2id, m=65536, t=3, p=4. Note the parameter order is `m,p,t`.
const LEGACY_ARGON2_HASH =
  "$argon2id$v=19$m=65536,p=4,t=3$SamcfUYMTyyMdsuU9bZcxw$1o6L2NyAAVmT/FeBhnsaNm38cXP5zG/If5NZXy5ZFUw";

test("hashPassword returns an argon2id PHC string", async () => {
  const hash = await hashPassword("hunter2");

  assert.match(hash, /^\$argon2id\$v=19\$m=\d+,t=\d+,p=\d+\$[^$]+\$[^$]+$/);
});

test("hashPassword produces a unique salt/hash each time", async () => {
  const first = await hashPassword("hunter2");
  const second = await hashPassword("hunter2");

  assert.notEqual(first, second);
});

test("verifyPassword accepts the correct password", async () => {
  const hash = await hashPassword("hunter2");

  assert.equal(await verifyPassword(hash, "hunter2"), true);
});

test("verifyPassword rejects an incorrect password", async () => {
  const hash = await hashPassword("hunter2");

  assert.equal(await verifyPassword(hash, "hunter3"), false);
});

test("verifyPassword verifies hashes from the legacy argon2 npm package", async () => {
  assert.equal(await verifyPassword(LEGACY_ARGON2_HASH, "hunter2"), true);
  assert.equal(await verifyPassword(LEGACY_ARGON2_HASH, "wrong"), false);
});

test("verifyPassword rejects malformed and unsupported hashes", async () => {
  assert.equal(await verifyPassword("", "hunter2"), false);
  assert.equal(await verifyPassword("not-a-hash", "hunter2"), false);
  assert.equal(await verifyPassword("scrypt:abcd:ef01", "hunter2"), false);
  assert.equal(
    await verifyPassword(
      "$argon2id$v=16$m=65536,t=3,p=1$YWJjZGVmZ2hpamtsbW5vcA$YWJjZGVmZ2hpamtsbW5vcA",
      "hunter2",
    ),
    false,
  );
  assert.equal(
    await verifyPassword(
      "$argon2i$v=19$m=65536,t=3,p=1$YWJjZGVmZ2hpamtsbW5vcA$YWJjZGVmZ2hpamtsbW5vcA",
      "hunter2",
    ),
    false,
  );
});
